# Generated by Django 4.1.2 on 2022-10-17 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=20, verbose_name='Pavadinimas')),
                ('pastabos', models.CharField(max_length=20, verbose_name='Pastabos')),
            ],
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=20, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=20, verbose_name='Pavardė')),
                ('pareigos', models.CharField(max_length=20, verbose_name='Pareigos')),
            ],
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=20, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=20, verbose_name='Pavardė')),
                ('imone', models.CharField(max_length=20, verbose_name='Įmonė')),
                ('kontaktai', models.TextField(max_length=500, verbose_name='Kontaktai')),
            ],
        ),
        migrations.CreateModel(
            name='Saskaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('israsymo_data', models.DateField(verbose_name='Išrašymo data')),
                ('suma', models.PositiveIntegerField(max_length=100, verbose_name='Suma')),
            ],
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=20, verbose_name='Pavadinimas')),
                ('pradzios_data', models.DateField(verbose_name='Pradžios data')),
                ('pabaigos_data', models.DateField(verbose_name='Pabaigos data')),
                ('darbas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.darbas')),
                ('darbuotojas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.darbuotojas')),
                ('klientas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.klientas')),
                ('saskaita_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektai.saskaita')),
                ('vadovas_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
