# Generated by Django 4.1.2 on 2022-10-18 05:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0002_alter_darbas_options_alter_darbuotojas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
