# Generated by Django 4.1.2 on 2022-10-18 05:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0003_projektas_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projektas',
            name='description',
        ),
        migrations.AddField(
            model_name='projektas',
            name='aprasymas',
            field=tinymce.models.HTMLField(null=True, verbose_name='Aprasymas'),
        ),
    ]
